入门
---------------

这部分指南旨在教你如何搭建你自己的Python开发环境

.. toctree::
   :maxdepth: 2

   starting/which-python

- 正确安装Python

 .. toctree::
    :maxdepth: 1
    
    starting/install/win
    starting/install/linux
    starting/install/osx



编写牛逼的代码
------------------

这部分指南提供了一些编写Python时的好的经验与技巧

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   writing/reading
   writing/documentation
   writing/tests
   writing/gotchas
   writing/license



Scenario Guide( 不知道怎么翻译准确 )
--------------

这部分指南描述了不同情况下使用Python模块和工具的建议

.. toctree::
   :maxdepth: 2

   scenarios/client
   scenarios/web
   scenarios/scrape
   scenarios/cli
   scenarios/gui
   scenarios/db
   scenarios/network
   scenarios/admin
   scenarios/ci
   scenarios/speed
   scenarios/scientific
   scenarios/imaging
   scenarios/xml


Shipping Great Code( 维护代码？部署代码？不会翻译了 )
-------------------

这部分指南将教你如何部署自己的Python代码

.. toctree::
   :maxdepth: 2

   shipping/packaging
   shipping/freezing


开发环境
-----------------------

.. toctree::
   :maxdepth: 2

   dev/env
   dev/virtualenvs




备注
----------------

这部分指南是最枯燥的部分，包含一些Python的背景知识

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/learning
   intro/documentation
   intro/news




--------------------------------------

Contribution notes and legal information are here (for those interested).( 这句不会翻译 )

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide





